package com.shageldi.fitfriend.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
class AppColorScheme(
    val mainColor: Color,
    val shade1Color: Color,
    val shade2Color: Color,
    val gradient1: List<Color>,
    val gradient2: List<Color>,
    val gradient3: List<Color>,
    val gradient4: List<Color>,
    val lowOpacity: Color,
    val lowOpacityWhite: Color,
    val textColor: Color,
    val whiteTextColor: Color,
    val backgroundColor: Color,
    val backgroundColor2: Color,
    val white: Color,
    val strokeLanding: Color,
    val stroke: Color,
    val gray1: Color,
    val gray2: Color,
    val gray3: Color,
    val overlay: Color,
    val red: Color,
    val green: Color,
    val greenShade: Color,
    val successBg: Color,
    val errorBg: Color,
    val warningBg: Color,
    val checkingBg: Color,
    val success: Color,
    val error: Color,
    val warning: Color,
    val checking: Color,
)

val appLightColorSchema = AppColorScheme(
    mainColor = Color(0xFFBBF246),
    shade1Color = Color(0xFFF6F8FE),
    shade2Color = Color(0xFF5B87EF),
    gradient1 = listOf(
        Color(0xFF1856E7),
        Color(0xFF5D89EF),
    ),
    gradient2 = listOf(
        Color(0xFFEBECF2),
        Color(0xFFFFFFFF),
    ),
    gradient3 = listOf(
        Color(0xFFFFFFFF),
        Color(0xFF82A8FF),
    ),
    gradient4 = listOf(
        Color(0xFFFFFFFF),
        Color(0xFFFFFFFF),
        Color(0xFFFFFFFF),
        Color(0xFF82A8FF),
    ),
    lowOpacity = Color(0xFF05112E).copy(alpha = 0.2f),
    lowOpacityWhite = Color(0xFFFFFFFF).copy(alpha = 0.4f),
    textColor = Color(0xFF05112E),
    whiteTextColor = Color(0xFFFFFFFF),
    backgroundColor = Color(0xFFFFFFFF),
    backgroundColor2 = Color(0xFFF6F7FA),
    white = Color(0xFFFFFFFF),
    strokeLanding = Color(0xFFE8EDFC),
    stroke = Color(0xFFE7E7EC),
    gray1 = Color(0xFFECEEF4),
    gray2 = Color(0xFFCDCCD2),
    gray3 = Color(0xFF808080),
    overlay = Color(0xFF000000).copy(alpha = 0.4f),
    red = Color(0xFFF90808),
    green = Color(0xFF68A192),
    greenShade = Color(0xFFEAF9F5),
    successBg = Color(0xFF34D399).copy(alpha = 0.2f),
    errorBg = Color(0xFFFB7185).copy(alpha = 0.2f),
    warningBg = Color(0xFFFACC15).copy(alpha = 0.2f),
    checkingBg = Color(0xFF567EFE).copy(alpha = 0.1f),
    success = Color(0xFF56CE56),
    error = Color(0xFFBE022B),
    warning = Color(0xFFF3A852),
    checking = Color(0xFF567EFE)
)

val appDarkColorSchema = AppColorScheme(
    mainColor = Color(0xFFBBF246),
    shade1Color = Color(0xFF1F1F1F),
    shade2Color = Color(0xFF262626),
    gradient1 = listOf(
        Color(0xFF161616),
        Color(0xFF161616),
    ),
    gradient2 = listOf(
        Color(0xFF404040).copy(alpha = 0.1f),
        Color(0xFF404040),
    ),
    gradient3 = listOf(
        Color(0xFF161616),
        Color(0xFF515151),
    ),
    gradient4 = listOf(
        Color(0xFF161616),
        Color(0xFF161616),
        Color(0xFF161616),
        Color(0xFF515151),
    ),
    lowOpacity = Color(0xFF4B4B4B).copy(alpha = 0.2f),
    lowOpacityWhite = Color(0xFFFFFFFF).copy(alpha = 0.4f),
    textColor = Color(0xFFFFFFFF),
    whiteTextColor = Color(0xFF161616),
    backgroundColor = Color(0xFF161616),
    backgroundColor2 = Color(0xFF333333),
    white = Color(0xFFFFFFFF),
    strokeLanding = Color(0xFF333333),
    stroke = Color(0xFF333333),
    gray1 = Color(0xFF4D4D4D),
    gray2 = Color(0xFF999999),
    gray3 = Color(0xFFA6A6A6),
    overlay = Color(0xFF000000).copy(alpha = 0.4f),
    red = Color(0xFFF90808),
    green = Color(0xFF13FFC1),
    greenShade = Color(0xFF0B2820),
    successBg = Color(0xFF34D399).copy(alpha = 0.2f),
    errorBg = Color(0xFF9F0404).copy(alpha = 0.2f),
    warningBg = Color(0xFFFACC15).copy(alpha = 0.2f),
    checkingBg = Color(0xFF567EFE).copy(alpha = 0.1f),
    success = Color(0xFF56CE56),
    error = Color(0xFFBE022B),
    warning = Color(0xFFF3A852),
    checking = Color(0xFF567EFE)
)